### ISSUE TITLE
infinite-scroll

### ISSUE THREAD

**Issue by lorenzodianni** [qwentes-team/agnostic#20]
Prevedere un componente per gestire l'infinite scroll all'interno di un listato

**Comment by matteobarone** [comment]
@lorenzodianni @robertagardiman
Secondo voi è meglio fare una cosa stile Heaven (quindi infinite scroll classico a cui siamo abituati), oppure utilizzare Angular CDK con il virtual scroll? [(esempio)](https://medium.com/@zainzafar/how-to-use-virtual-scrolling-using-angular-7-cdk-9802110111fa)

Oppure fare un componente che li gestisce entrambi?

**Comment by lorenzodianni** [comment]
Partirei con Angular CDK ed il suo virtual scroll, se poi vediamo che per qualche motivo ci dovesse servire quello classico, lo implementiamo successivamente (nello stesso componente)

**Comment by matteobarone** [comment]
@lorenzodianni  lo ScrollingModule di Angular CDK per il virtual scroll vuole obbligatoriamente un'altezza fissa di default (vuole l'attributo itemSize che deve essere un numero).

C'è un workaround, con cdk-experimental puoi metter l'attributo autofix, e poi puoi mettere l'altezza che vuoi via css.

[Stackblitz di esempio](https://stackblitz.com/edit/cdk-virtual-scroll-simple-autosize?file=app%2Fapp.module.ts)

Che fasen?

**Comment by lorenzodianni** [comment]
Come non detto, non avevo considerato l'altezza fissa..
Quindi facciamo 2 componenti, un infinite-scroll ed un virtual-scroll

Non usiamo l'experimental, tanto nel caso in cui dovesse diventare lo standard dovrebbe essere un attimo togliere l'attributo itemSize 💪

**Comment by matteobarone** [comment]
Ottimo! Usiamo questa per infinite-scroll?

[ngx-infinite-scroll](https://github.com/orizens/ngx-infinite-scroll)
